# Generated by Django 2.0 on 2020-05-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='liked_time',
            new_name='liked_num',
        ),
    ]
