# Generated by Django 2.0 on 2020-04-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200420_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reded_num',
            field=models.IntegerField(default=0),
        ),
    ]
