# Generated by Django 2.0 on 2020-04-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_reded_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='reded_num',
            new_name='readed_num',
        ),
    ]
